<template>
  <div style="width: 600px;height: 600px;" ref="chartRef">

  </div>
</template>

<script>
  export default {
    name: 'coolSimple',
    mounted() {
      this.showChart()
    },
    methods: {
      showChart() {
        let options = this.getOptions()
        let echarts = this.$echarts.init(this.$refs.chartRef)
        echarts.setOption(options)
      },
      getOptions() {
        return {
          "xAxis":[
            {
              "max":"100",
              "splitLine":{
                "show":false
              },
              "axisLine":{
                "show":false
              },
              "axisLabel":{
                "show":false
              },
              "axisTick":{
                "show":false
              }
            },
            {
              "max":1,
              "splitLine":{
                "show":false
              },
              "axisLine":{
                "show":false
              },
              "axisLabel":{
                "show":false
              },
              "axisTick":{
                "show":false
              }
            }
          ],
          "grid":{
            "left":80,
            "top":10,
            "right":100,
            "bottom":10,
            "containLabel":true
          },
          "yAxis":[
            {
              "type":"category",
              "inverse":false,
              "data":[
                {
                  "name":"衡阳市",
                  "value":90.91
                },
                {
                  "name":"株洲市",
                  "value":100
                },
                {
                  "name":"常德市",
                  "value":100
                },
                {
                  "name":"郴州市",
                  "value":100
                },
                {
                  "name":"益阳市",
                  "value":100
                },
                {
                  "name":"娄底市",
                  "value":100
                },
                {
                  "name":"长沙市",
                  "value":75
                },
                {
                  "name":"耒阳市",
                  "value":88.89
                },
                {
                  "name":"上海市",
                  "value":75
                },
                {
                  "name":"北京市",
                  "value":100
                },
                {
                  "name":"天津市",
                  "value":88.89
                },
                {
                  "name":"湖南省",
                  "value":93.33
                }
              ],
              "axisLine":{
                "show":false
              },
              "axisTick":{
                "show":false
              },
              "axisLabel":{
                "show":false
              }
            }
          ],
          "series":[
            {
              "type":"bar",
              "barWidth":10,
              "legendHoverLink":false,
              "silent":true,
              "itemStyle":{
                "normal":{
                  "barBorderRadius":30,
                  "color":{
                    "type":"linear",
                    "x":0,
                    "y":0,
                    "x2":1,
                    "y2":0,
                    "colorStops":[
                      {
                        "offset":0,
                        "color":"rgba(64,187,238,1)"
                      },
                      {
                        "offset":1,
                        "color":"rgba(64,233,238,1)"
                      }
                    ]
                  }
                }
              },
              "label":{
                "normal":{
                  "show":true,
                  "position":"left",
                  "formatter":"{b}",
                  "textStyle":{
                    "color":"#fff",
                    "fontSize":18
                  }
                }
              },
              "data":[
                {
                  "name":"衡阳市",
                  "value":90.91
                },
                {
                  "name":"株洲市",
                  "value":100
                },
                {
                  "name":"常德市",
                  "value":100
                },
                {
                  "name":"郴州市",
                  "value":100
                },
                {
                  "name":"益阳市",
                  "value":100
                },
                {
                  "name":"娄底市",
                  "value":100
                },
                {
                  "name":"长沙市",
                  "value":75
                },
                {
                  "name":"耒阳市",
                  "value":88.89
                },
                {
                  "name":"上海市",
                  "value":75
                },
                {
                  "name":"北京市",
                  "value":100
                },
                {
                  "name":"天津市",
                  "value":88.89
                },
                {
                  "name":"湖南省",
                  "value":93.33
                }
              ],
              "z":1,
              "animationEasing":"elasticOut"
            },
            {
              "type":"pictorialBar",
              "symbol":"rect",
              "symbolBoundingData":"100",
              "itemStyle":{
                "normal":{
                  "color":"none"
                }
              },
              "label":{
                "normal":{
                  "padding":[
                    4,
                    0,
                    0,
                    6
                  ],
                  formatter: e => "{a| " + e.data + " }{b|  %}",
                  "rich":{
                    "a":{
                      "color":"#fff",
                      "width":50,
                      "align":"center",
                      "fontSize":18
                    },
                    "b":{
                      "color":"#fff",
                      "fontSize":16
                    }
                  },
                  "position":"right",
                  "distance":0,
                  "show":true
                }
              },
              "data":[
                90.91,
                100,
                100,
                100,
                100,
                100,
                75,
                88.89,
                75,
                100,
                88.89,
                93.33
              ],
              "z":0,
              "animationEasing":"elasticOut"
            },
            {
              "name":"背景",
              "type":"bar",
              "barGap":"-100%",
              "data":[
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1
              ],
              "xAxisIndex":1,
              "barWidth":8,
              "itemStyle":{
                "normal":{
                  "color":"#1b2f4f",
                  "barBorderRadius":30
                }
              },
              "z":0
            }
          ]
        }
      },
    },
  }
</script>

<style scoped>

</style>
