<template>
  <div style="width: 600px;height: 600px;" ref="chartRef">

  </div>
</template>

<script>
  export default {
    name: 'coolSimple',
    mounted() {
      this.showChart()
    },
    methods: {
      showChart() {
        let options = this.getOptions()
        let echarts = this.$echarts.init(this.$refs.chartRef, 'normal')
        echarts.setOption(options)
      },
      getOptions() {
        return {
          "grid":{
            "left":0,
            "top":60,
            "right":0,
            "bottom":10,
            "containLabel":true
          },
          "legend":{
            "data":[
              "基本农田",
              "水保林",
              "经果林",
              "种草",
              "封育治理",
              "其它"
            ],
            "bottom":10,
            "left":"center",
            "icon":"circle",
            "itemWidth":8,
            "itemHeight":8,
            "textStyle":{
              "color":"#fff",
              "fontSize":14
            },
            "top":10
          },
          "xAxis":{
            "data":[
              "2014",
              "2015",
              "2016",
              "2017",
              "2018",
              "2019",
              "2020(预计)"
            ],
            "axisLabel":{
              "textStyle":{
                "color":"#fff",
                "fontSize":12
              },
              "interval":0
            },
            "axisTick":{
              "inside":true,
              "show":true,
              "color":"#5A6362"
            },
            "axisLine":{
              "show":true,
              "lineStyle":{
                "color":"#5A6362"
              }
            },
            "z":10
          },
          "yAxis":{
            "axisLine":{
              "show":false
            },
            "axisTick":{
              "show":false
            },
            "axisLabel":{
              "textStyle":{
                "color":"#fff",
                "fontSize":12
              }
            },
            "splitLine":{
              "lineStyle":{
                "color":"#16354a"
              }
            }
          },
          "dataZoom":[
            {
              "type":"inside",
              "show":true,
              "height":20,
              "left":"10%",
              "right":"10%",
              "bottom":10,
              "startValue":-5,
              "endValue":6,
              "textStyle":{
                "color":"#000",
                "fontSize":11
              }
            }
          ],
          "series":[
            {
              "type":"bar",
              "showBackground":true,
              "backgroundStyle":{
                "color":"rgba(19,62,101,0.3)"
              },
              "itemStyle":{
                "color":"red"
              },
              "data":[
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
              ]
            },
            {
              "name":"基本农田",
              "type":"line",
              "smooth":0.6,
              "lineStyle":{
                "color":"rgba(1,171,255,1)",
                "width":2
              },
              "areaStyle":{
                "color":{
                  "type":"linear",
                  "x":0,
                  "y":0,
                  "x2":0,
                  "y2":1,
                  "colorStops":[
                    {
                      "offset":0,
                      "color":"rgba(1,171,255,1)"
                    },
                    {
                      "offset":1,
                      "color":"rgba(1,171,255,1)"
                    }
                  ],
                  "global":false
                },
                "opacity":0.1
              },
              "symbol":"none",
              "data":[
                "43.19 ",
                "67.51 ",
                21.53,
                53.31,
                18.49,
                23.52,
                25.63
              ]
            },
            {
              "name":"水保林",
              "type":"line",
              "smooth":0.6,
              "lineStyle":{
                "color":"rgba(0,255,255,1)",
                "width":2
              },
              "areaStyle":{
                "color":{
                  "type":"linear",
                  "x":0,
                  "y":0,
                  "x2":0,
                  "y2":1,
                  "colorStops":[
                    {
                      "offset":0,
                      "color":"rgba(0,255,255,1)"
                    },
                    {
                      "offset":1,
                      "color":"rgba(0,255,255,1)"
                    }
                  ],
                  "global":false
                },
                "opacity":0.1
              },
              "symbol":"none",
              "data":[
                "401.31 ",
                "326.36 ",
                195.28,
                296.09,
                266.7,
                284.3,
                272.6
              ]
            },
            {
              "name":"经果林",
              "type":"line",
              "smooth":0.6,
              "lineStyle":{
                "color":"rgba(255,196,59,1)",
                "width":2
              },
              "areaStyle":{
                "color":{
                  "type":"linear",
                  "x":0,
                  "y":0,
                  "x2":0,
                  "y2":1,
                  "colorStops":[
                    {
                      "offset":0,
                      "color":"rgba(255,196,59,1)"
                    },
                    {
                      "offset":1,
                      "color":"rgba(255,196,59,1)"
                    }
                  ],
                  "global":false
                },
                "opacity":0.1
              },
              "symbol":"none",
              "data":[
                "468.92 ",
                "220.72 ",
                137.76,
                187.27,
                182.6,
                184.5,
                176.2
              ]
            },
            {
              "name":"种草",
              "type":"line",
              "smooth":0.6,
              "lineStyle":{
                "color":"rgba(24,238,122,1)",
                "width":2
              },
              "areaStyle":{
                "color":{
                  "type":"linear",
                  "x":0,
                  "y":0,
                  "x2":0,
                  "y2":1,
                  "colorStops":[
                    {
                      "offset":0,
                      "color":"rgba(24,238,122,1)"
                    },
                    {
                      "offset":1,
                      "color":"rgba(24,238,122,1)"
                    }
                  ],
                  "global":false
                },
                "opacity":0.1
              },
              "symbol":"none",
              "data":[
                "42.28 ",
                "13.17 ",
                9.48,
                23.77,
                23.65,
                23.28,
                25.72
              ]
            },
            {
              "name":"封育治理",
              "type":"line",
              "smooth":0.6,
              "lineStyle":{
                "color":"rgba(255,79,152,1)",
                "width":2
              },
              "areaStyle":{
                "color":{
                  "type":"linear",
                  "x":0,
                  "y":0,
                  "x2":0,
                  "y2":1,
                  "colorStops":[
                    {
                      "offset":0,
                      "color":"rgba(255,79,152,1)"
                    },
                    {
                      "offset":1,
                      "color":"rgba(255,79,152,1)"
                    }
                  ],
                  "global":false
                },
                "opacity":0.1
              },
              "symbol":"none",
              "data":[
                "1110.44 ",
                "943.13 ",
                795.76,
                380.04,
                662.29,
                728.3,
                842.1
              ]
            },
            {
              "name":"其它",
              "type":"line",
              "smooth":0.6,
              "lineStyle":{
                "color":"rgba(255,47,255,1)",
                "width":2
              },
              "areaStyle":{
                "color":{
                  "type":"linear",
                  "x":0,
                  "y":0,
                  "x2":0,
                  "y2":1,
                  "colorStops":[
                    {
                      "offset":0,
                      "color":"rgba(255,47,255,1)"
                    },
                    {
                      "offset":1,
                      "color":"rgba(255,47,255,1)"
                    }
                  ],
                  "global":false
                },
                "opacity":0.1
              },
              "symbol":"none",
              "data":[
                "162.27 ",
                "153.24 ",
                27.92,
                183.36,
                149.64,
                118.6,
                132.75
              ]
            }
          ],
          "color":[
            "rgba(1,171,255,1)",
            "rgba(0,255,255,1)",
            "rgba(255,196,59,1)",
            "rgba(24,238,122,1)",
            "rgba(255,79,152,1)",
            "rgba(255,47,255,1)"
          ]
        }
      },
    },
  }
</script>

<style scoped>

</style>
